geokrety/geokrety-website

export.php

Let's use this PR, so everyone can familiarize with github review process.

Fix #10: Full database export consume to much memory

---

website/adduser.php
website/majluj.php
website/new_password.php

Seen in https://crowdin.com/translate/geokrety/25/en-de#9972
Do not merge before #64 is merged.

Fix typo in string

---

install.sh
update.sh

- update: to preserve file ownership use compose again as workaround (docker cp from machine to container change ownership)
- fix cp quiet option for old versions of DockerToolbox
- no need to redeploy

docker compose / fix update website +quiet scp option

---

website/race_join.php

- increase geokret reference number input 6 => 7
- add error when geokret not found
- add try catch to handle error
- add insert error log

Fixes #80 cant join race

---

website/help/en/help.html

Comments from crowdin translator

Fix some help strings

---

.gitignore
website/templates/waypointy-translations.html

Import new waypoint translations

---

website/lib/geokrety/view/SocialGroups.class.php
website/templates/konfig-groups.php

For references, we use this library http://flag-icon-css.lip.is/

Use css flags instead of png files

---

website/defektoskop.php
website/lingering.php
website/recent_newscomments_fn.php

Fix icons urls 

---

website/ruchy.js
website/ruchy.php

Related #19.
It needed for the input after click coordinates buttons. Clear coordinates button will clear all inputs from other buttons.

Add clear coordinates button

---

website/szukaj.php

Related #145.
In the search form, form actions were combined GET/POST. All search form changed the action as GET so all variables pass through URL rather than form submit. It will fix the pagination issue.

Fix search pagination

---

website/race_join.php

Hi Geokrety! I just found your project via hacktoberfest label. The website looks really fun and enjoyable. I hope that I can help some of the parts.
This PR is related #2 . I added validating code for the joining race page. Please review the changes.

Fix validation of joining race

---

website/aktualizuj.php
website/majluj.php

I think we should be fine with this. @boly38 what do you think? Should we expect some weird behavior?

html entities decode username in mail and statpic

---

website/export.php
website/export2.php
website/export_oc.php

Let's relieve the database a little bit… those logs are not really useful

Disable some heavy logs

---

.travis.yml
scripts/qatests_hook.sh
scripts/qatests_wait.sh

- Fixes #199
- move travis scripts to scripts/

Travis build must not failed on QA timeout

---

.gitignore
.travis.yml
composer.json
composer.lock
scripts/qatests_hook.sh
tests/LDHelperTest.php
website/aktualizuj.php
website/composer.lock
website/index.php
website/konkret-tabelka.php
website/konkret.php
website/lib/LDHelper.class.php
website/lib/geokrety/domain/Konkret.class.php
website/lib/geokrety/domain/KonkretLog.class.php
website/sqlproc.php
website/ulicznik.php

- following #7 initial LdJson SEO feature
- increase ld-json version to 0.0.14 following torann/json-ld#42
- use new fields from 0.0.14 (publisher, lang, date)
- add konkret dedicated ldjson helper and test
- use full url for 'sameAs' field, that fixes #121
- manual tests with google tool https://search.google.com/structured-data/testing-tool/u/0/?hl=fr
- fix phpunit tests
- light irc notification format
--
branch 'boly38' updated , you could [test with google tool](https://search.google.com/structured-data/testing-tool/u/0/?hl=fr#url=https%3A%2F%2Fboly38.gk.kumy.org%2Fkonkret.php%3Fid%3D59532) a [konkret page](https://boly38.gk.kumy.org/konkret.php?id=59532).

Improve LdJson generation

---

.travis.yml

no qa tests on external PR

---

website/adduser.php
website/index.php
website/recent_moves.php
website/ruchy.php
website/szukaj-ajax.php
website/szukaj_kreta.php
website/templates/krety.html
website/templates/krety_logged_in.html

- welcome page
- menu
- ruchy
- adduser
- fixes #160

add html element ids for qa

---

.travis.yml
scripts/export-translations-github.sh

Let's install crowdin-cli from deb package

Fix #198: Install travis from deb package

---

composer.json
composer.lock
tests/CreditsTest.php
tests/SocialGroupsTest.php
tests/lib/TestUtil.php
website/halloffame.php
website/lib/geokrety/view/Credits.class.php
website/templates/konfig-credits.php
website/templates/konfig.php

- add way to generate credits table + unit test
- common test function in TestUtil
- add config-credits
- improve config icon_size, icon_style
- integrate into target page halloffame
- use CDN for logos files geokrety/GeoKrety-Static#2
- add CONFIG_CDN_LOGOS
- fixes #41

halloffame credits

---

configs/konfig-local.tmpl.php
docker/mariadb/00_database-create-geokrety-db.sql
website/defektoskop.php
website/ruchy.php

- update default schema that fixes #226

fix default values for geokrety/ruchy

---

website/__sentry.php
website/halloffame.php
website/smarty_start.php

This PR fixes #235 : no more duplicate credits
demo: https://boly38.gk.kumy.org/halloffame.php
(@kumy : please notice that rec DNS is not working)

fixes #235 duplicate credits

---

website/aktualizuj.php
website/api-login2secid.php
website/api-secid-change.php
website/czy_obserwowany.php
website/czysc.php
website/db.php
website/defektoskop.php
website/email_errors.php
website/fn_haslo.php
website/konkret-mapka.php
website/lost_mapka.php
website/mapka_kretow.php
website/obrazek.php
website/obserwuj.php
website/ostatnie_obrazki_uzytkownika.php
website/recent_comments_fn.php
website/recent_moves.php
website/recent_newscomments_fn.php
website/register.fn.php
website/templates/plugins/function.login_check.php
website/timeline.php
website/verify_mail.php
website/whoiskret.php
website/whoiswho.php
website/wybierz_jezyk.php

There was one more include consing trouble for #235. In the same time, I've also updated other files with same kind of change

Fix #235: Include conf once

---

website/lib/geokrety/domain/AbstractResponse.php
website/lib/geokrety/domain/ErrorResponse.php
website/lib/geokrety/service/JsonService.php
website/rest/konkret/trip/read.php

Fixes #278 rest trip json encoding non UTF8 content

Fixes #278 rest trip json encoding non UTF8 content

---

website/lib/geokrety/domain/AbstractResponse.php
website/lib/geokrety/domain/ErrorResponse.php
website/lib/geokrety/service/JsonService.php
website/rest/konkret/trip/read.php

- Fixes #278 rest trip json encoding non UTF8 content

Fixes #278 trip utf8 to prod

---

tests/D02TripRepositoryTest.php
tests/D03TripServiceTest.php
website/lib/geokrety/exception/NoDataException.php
website/lib/geokrety/repository/TripRepository.class.php
website/rest/konkret/trip/read.php

like the title said
> Fixes #283 catch NoDataException onTripUpdate

Fixes #283 catch NoDataException onTripUpdate

---

website/export.php
website/export2.php
website/export_oc.php
website/gkt/search_v3.php
website/ruchy.php

Let's better understand our traffic

Add tracker for directly accessed pages

---

gkShell/Dockerfile
gkShell/gk.sh

- use geokrety/website-legacy-base as base image following #291
- fix apache resource cp
you were right @kumy ; your update about image externalization simplify gkShell too :)

gkShell change image and fix apache cp

---

website/gkt/inventory.php
website/gkt/inventory_v3.php
website/gkt/search.php
website/gkt/search_v3.php
website/gkt2/inventory.php
website/gkt2/inventory_v3.php
website/gkt2/search.php
website/gkt2/search_v3.php
website/go2geo/go2geo.php
website/m/qr.php
website/templates/labels/index.php
website/templates/labels/label-2.php
website/templates/labels/label.php
website/templates/labels/label2.php
website/wybierz_jezyk.php

Fix #303: Drop old import of konfig-local.php 
Add sentry to standalone pages

Fix issue #303

---

website/funkcje.js
website/race_add.js
website/ruchy.php
website/szukaj-ajax.php
website/templates/konfig.php

Quick Fix #309 allow 4 characters as waypointy code
Best effort: I'm not super fan of javascript side wich doesn't rely on new config `CONFIG_WAYPOINTY_MIN_LENGTH`, but it would be costly to refactor this part, and I dislike javascript global vars too :)
NB/ special thanks @kumy for the issue details :)

Quick Fix #309 allow 4 characters as waypointy code

---

website/molehole.php

This is only a quick win to help one of our user.
We'll need to have a general workflow for that

Issue #393 Manually add new Hotels we know about

---

website/lib/GKDB.class.php
website/lib/geokrety/service/CountryService.php
website/lib/geokrety/service/ElevationService.php

Those were used by PR geokrety/geokrety-scripts/pull/11

Backport features from new-theme

---

.travis.yml
composer.json
composer.lock
website/lib/GKDB.class.php

Fix travis-ci - workaround mariadb install problem

---

website/templates/konfig.php

reverted to default value unconditionnally

workaround #448

---

website/rzeczy/messages.po.txt
website/templates/konfig.php

deploy to prod

---

gkShell/Dockerfile

Minor
- adapt gk shell compose file for new theme

gkShell Dockerfile update HEALTHCHECK

---

website/app-templates/smarty/elements/move_as_list.tpl
website/app-templates/smarty/navbar.tpl
website/app-templates/smarty/pages/home.tpl
website/app/GeoKrety/Controller/Home.php
website/app/GeoKrety/Service/Config.php

new-theme template must be resilient when no data
- Fix #485 improve smarty tpl and Home while there is no data to show
@kumy don't hesitate to rock my suggest if we could simplify / I dont know very well tpl feature (ex. multiple if conditon, function overrides...)

Fix #485 improve smarty tpl and Home while there is no data to show

---

docker-compose.local.yml

Fix docker-compose minio service volumes and environment indentation

Fix docker-compose

---

README.md
website/app/GeoKrety/Controller/HallOfFame.php

As discussed in https://github.com/geokrety/geokrety-website/pull/514 another PR for the new theme
Can you please review @kumy @boly38 ?

Add f3 to halloffame and README

---

README.md

Followup of https://github.com/geokrety/geokrety-website/pull/517

change image size in README

---

.gitignore
website/app-templates/smarty/pages/hall_of_fame.tpl
website/app/GeoKrety/Controller/HallOfFame.php

Fix #516 contributors links when no data
PS/ and add `minio_data/` into .gitignore

Fix #516 contributors links when no data

---

.travis.yml

> PHP 7.4 is scheduled to be released on November 28, 2019. It’s the next PHP 7 minor release and should once again boost performance and improve code readability/maintainability.

Prepare for php 7.4

---

scripts/app_version_wait.sh

This reverts commit 7b9ff3a693c29965cd976899d95387fd4ac3f124.
qaWait still to fix :)

Revert "travis: app version wait is now strict"

---

scripts/app_version_wait.sh

- fix app_version_wait negative case
- app_version_wait strict again

Fix #531 app version wait script

---

website/ruchy.php

Thanks Ezio Paglia for the responsible disclosure via openbugbounty.org

Fix XSS issues

---

website/ruchy.php

That's the problem I described previously in the email thread titled "Small API suggestion improvement" (yeah, there's a typo in the subject).
I suspect this should fix it, but I have not verified it (I just edited the code in the repo, I did not run it)! If you could spare some time to verify this fix please, and pull it to prod, I think some users would be grateful!

Crude fix for the `?waypoint` query param not being loaded properly

---

INSTALL.md
docker-compose.local.yml
docker/mariadb/00_database-create-geokrety-db.sql

Feels like I was the only one who was trying this out, current steps were not really working, so need to add a few more...

doc: fix local installation readme

---

geokrety-entrypoint.sh
minio/init.sh

Fix minio perms

---

website/app-templates/smarty/js/geokrety/geokrety_details_map.tpl.js

the travel was only shown on first page

fix: Warkaround map pins issue with multiple pages

---

website/app/GeoKrety/Controller/Pages/GeokretMovesGeojson.php

fix: Limit geojson moves to 500 results

---

website/app-templates/smarty/blocks/geokret/details.tpl
website/app-templates/smarty/plugins/modifier.country_track.php
website/app/GeoKrety/Model/Geokret.php

feat: Add GeoKrety "Country Track"

---

website/app/GeoKrety/Controller/Pages/Home.php

Only show new GK with an owner on home page

fix: Show on home page the newly created GK with an owner

---

tests-qa/acceptance/300_LegacyBridges/210_ruchy.robot
website/app-templates/smarty/admin/pages/geokrety_generator.tpl
website/app-templates/smarty/blocks/found_geokret.tpl
website/app-templates/smarty/blocks/geokret/found_it.tpl
website/app-templates/smarty/forms/geokrety_labels.tpl
website/app-templates/smarty/forms/move.tpl
website/app-templates/smarty/js/maxlenght.tpl.js
website/app/GeoKrety/Service/Config.php
website/app/GeoKrety/Service/SecretCode.php
website/app/GeoKrety/Service/Validation/TrackingCode.php

Allow Tracking Codes with 7 chars

fix #693: Allow Tracking Codes with 7 chars

---

website/app/GeoKrety/Email/BasePHPMailer.php

This should help really sending mail!

fix: Really send mail on production instance 🤣

---

tests-qa/acceptance/030_Geokrety/010_GeokretyCreation/070_EditGeoKretBirth.robot
tests-qa/acceptance/050_Moves/__init__.robot
website/app/validators.php

Closes #1015
Still need to check why the unit tests didn't caught it

fix: Database validator wasn't GK birthdates aware

---

tests-qa/acceptance/030_Geokrety/010_GeokretyCreation/040_GeoKretType.robot
tests-qa/acceptance/030_Geokrety/010_GeokretyCreation/060_EditGeoKret.robot
tests-qa/acceptance/030_Geokrety/010_GeokretyCreation/070_EditGeoKretBirth.robot
tests-qa/acceptance/030_Geokrety/040_Collectible/010_ManageFlag.robot
tests-qa/acceptance/ressources/Devel.robot
tests-qa/acceptance/ressources/vars/Urls.robot
website/app-templates/smarty/blocks/user/details.tpl
website/app-templates/smarty/elements/geokrety_as_list_recently_born.tpl
website/app-templates/smarty/elements/geokrety_as_list_user_inventory.tpl
website/app-templates/smarty/elements/geokrety_as_list_user_owned_geokrety.tpl
website/app-templates/smarty/elements/geokrety_as_list_user_watched_geokrety.tpl
website/app-templates/smarty/extension/SmartyGeokretyExtension.php
website/app-templates/smarty/help-pages/en/help.html
website/app-templates/smarty/navbar-left.tpl
website/app-templates/smarty/pages/help_api.tpl
website/app-templates/smarty/pages/home.tpl
website/app/GeoKrety/Assets.php
website/app/GeoKrety/Controller/Devel/DatabaseSeed.php
website/app/GeoKrety/Controller/Pages/HallOfFame.php
website/app/GeoKrety/GeokretyType.php
website/db/migrations/20240720180654_new_gk_types.php
website/db/tests-copy-schema-geokrety-to-tests.sh
website/db/tests-srtm-import.sh
website/db/tests/test-22-sessions.sql
website/db/tests/test-30-moves_type.sql
website/db/tests/test-52-geokret-type.sql
website/public/app-ui/css/app.scss

such GK types will be automatically marked as non-collectible

feat: Add support for new GK Types: pebble, car, playing card, dog

---

.pre-commit-config.yaml
website/app/GeoKrety/Controller/Pages/UserUpdatePassword.php

fix: Allow users without an email to set a password

---

tests/unit/app/GeoKrety/Emails/EmailChangeTest.php
website/app/GeoKrety/Email/EmailChange.php

fix: Allow user to change his email whatever the email status is

---

website/app-templates/smarty/emails/daily-mail.tpl
website/app-templates/smarty/extension/SmartyGeokretyExtension.php

fix: Use png images in daily mails

---

tests-qa/acceptance/010_UserRegistration/012_EmailBanner.robot
tests-qa/acceptance/ressources/Authentication.robot
website/app-templates/smarty/banners/registration_spam_filter.tpl
website/app-templates/smarty/forms/registration.tpl
website/app-templates/smarty/js/registration/registration.events.tpl.js
website/app-templates/smarty/pages/registration.tpl

fix: Display agresive spam filter rule warning banner

---

tests/unit/app/GeoKrety/Service/MarkdownTest.php
website/app/GeoKrety/Service/Markdown.php

fix: drop unused code and fix regex

---

tests-qa/acceptance/230_Moves/000_PostFast.robot
tests-qa/acceptance/230_Moves/060_Location.robot
tests-qa/acceptance/230_Moves/065_LocationOptional.robot
tests-qa/acceptance/230_Moves/080_FullForm.robot
tests-qa/acceptance/ressources/vars/moves.yml
website/app-templates/smarty/js/moves/geokret_move.tpl.js
website/app-templates/smarty/js/moves/geokret_move.validation.tpl.js
website/app/GeoKrety/LogType.php
website/app/GeoKrety/Service/Moves.php
website/db/migrations/20250215172251_seen_dontrequire_coordinates.php
website/db/tests-copy-schema-geokrety-to-tests.sh
website/db/tests-copy-schema-tests-to-geokrety.sh
website/db/tests/test-20-functions.sql
website/db/tests/test-30-moves-waypoint.sql
website/db/tests/test-30-moves_type.sql

feat: Allow "Meet" logtype without coordinates

---

website/app-templates/smarty/pages/help_api.tpl

fix: Correct API doc for export_oc

---

tests-qa/acceptance/210_LegacyBridges/210_ruchy.robot
tests-qa/acceptance/230_Moves/090_MoveEdit.robot
website/app-templates/smarty/forms/move.tpl
website/app-templates/smarty/js/moves/geokret_move.tpl.js
website/app/GeoKrety/Service/Moves.php
website/app/validators.php

Attempt to fix case where:
birth date is: `2025-04-28T23:35:00+00:00`
move date is: `2025-04-28T18:09:00-06:00`

fix: Fix timezone issue in GK move to birth date validator

---

website/app-templates/smarty/forms/move.tpl
website/app-templates/smarty/pages/help_api.tpl

fix: Add bulk logging info in API doc

---

tests-qa/acceptance/230_Moves/080_FullForm.robot
tests-qa/acceptance/ressources/ComponentsLocator.robot
tests-qa/acceptance/ressources/CustomActions.robot
website/app-templates/smarty/forms/move.tpl
website/app-templates/smarty/js/moves/geokret_move.tpl.js
website/app/GeoKrety/Controller/Pages/MoveCreate.php

feat: Add Save date and comment checkbox

---

tests-qa/acceptance/060_MovesComments/30_Missing.robot
website/app-templates/smarty/elements/move.tpl
website/app/GeoKrety/Controller/Pages/MoveCommentCreate.php
website/app/GeoKrety/GeokretyType.php
website/app/GeoKrety/LogType.php
website/app/GeoKrety/Model/Move.php
website/db/migrations/20250905175604_log_type_missing.php
website/db/tests/test-20-functions.sql
website/db/tests/test-81-moves-comments-missing.sql

fix: Allow missing on more move types

---

website/app-templates/smarty/blocks/geokret/found_it.tpl
website/app-templates/smarty/elements/label_form_common.tpl
website/app-templates/smarty/elements/label_preview.tpl
website/app-templates/smarty/forms/geokret.tpl
website/app-templates/smarty/forms/geokret_label.tpl
website/app-templates/smarty/js/_label_preview.js
website/app-templates/smarty/pages/geokret_create.tpl
website/app-templates/smarty/pages/geokret_label.tpl
website/app/GeoKrety/Assets.php
website/app/GeoKrety/Controller/Pages/GeokretCreate.php
website/app/GeoKrety/Controller/Pages/GeokretEdit.php
website/app/GeoKrety/Controller/Pages/GeokretLabel.php
website/app/GeoKrety/Controller/Pages/GeokretyLabels.php
website/app/GeoKrety/Model/Geokret.php
website/app/GeoKrety/Service/Config.php
website/app/GeoKrety/Service/Labels/Image.php
website/app/GeoKrety/Service/RateLimit.php
website/db/migrations/20250906141803_label_languages.php

fix: render real label in preview + rate limit

---

website/app-templates/smarty/help-pages/en/help.html
website/app/GeoKrety/Controller/Pages/Base.php
website/app/GeoKrety/Controller/Pages/Help.php
website/app/GeoKrety/Service/Config.php
website/db/migrations/20250916153853_fix_geokret_near_home.php

fix: Correct the view since update of GK markable as missing
